import { useEffect, useMemo, useState } from "react";
import { Download, FileWarning, Filter, GitCompareArrows, Network, Timer, ZoomIn } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { evidenceForRequirement, globalEvidenceForProject, type BenchmarkRun, type ProjectId, type RequirementStatus } from "@agentbench/shared";
import { api, artifactUrl, messageOf } from "../services/api";
import { EmptyState, ErrorNotice, PageHeader, StatusBadge } from "../components/Ui";

export function EvidencePage() {
  const { id = "" } = useParams();
  const [run, setRun] = useState<BenchmarkRun | null>(null);
  const [error, setError] = useState("");
  const [selectedId, setSelectedId] = useState("");
  const [filter, setFilter] = useState<RequirementStatus | "all">("all");
  const [zoom, setZoom] = useState<string | null>(null);
  useEffect(() => { api.getRun(id).then((value) => { setRun(value); setSelectedId(value.results?.requirementMatrix[0]?.requirement.id ?? ""); }).catch((value) => setError(messageOf(value))); }, [id]);
  const matrix = useMemo(() => run?.results?.requirementMatrix ?? [], [run]);
  const filtered = useMemo(() => matrix.filter((entry) => filter === "all" || entry.projectA.status === filter || entry.projectB.status === filter), [matrix, filter]);
  const selected = matrix.find((entry) => entry.requirement.id === selectedId) ?? filtered[0];
  if (!run?.results) return <div className="page"><PageHeader eyebrow="EVIDENCE CENTER" title="需求追踪与证据" />{error ? <ErrorNotice message={error} /> : <div className="loading-line">正在读取测试证据…</div>}</div>;
  const result = run.results;
  const tests = selected ? run.testCases.filter((testCase) => selected.testCaseIds.includes(testCase.id)) : [];
  const projectView = (projectId: ProjectId, index: number) => {
    const project = result.projectResults[index];
    const evidence = project && selected ? evidenceForRequirement(project, selected.testCaseIds) : { testResults: [], logs: [], requestFailures: [], artifacts: [] };
    const screenshots = evidence.artifacts.filter((artifact) => artifact.type === "screenshot");
    return <article className="evidence-project" key={projectId}><header><div><span className="project-letter">{projectId === "project-a" ? "A" : "B"}</span><div><small>{run.projects[index]?.sourceAgent}</small><h2>{run.projects[index]?.name}</h2></div></div>{selected && <StatusBadge status={projectId === "project-a" ? selected.projectA.status : selected.projectB.status} />}</header><div className="evidence-tests">{evidence.testResults.map((testResult) => <div className="evidence-test" key={`${testResult.testCaseId}-${testResult.viewport ?? "desktop"}`}><div><strong>{testResult.testCaseId}</strong><StatusBadge status={testResult.status} /><span><Timer />{testResult.durationMs} ms</span></div>{testResult.error && <p><FileWarning />{testResult.error}</p>}<ol>{testResult.steps.map((step) => <li key={`${step.index}-${step.viewport}`} className={step.status}><span>{step.index + 1}</span><code>{step.action}</code><small>{step.viewport} · {step.durationMs} ms</small>{step.error && <p>{step.error}</p>}</li>)}</ol></div>)}</div><div className="evidence-images">{screenshots.map((artifact) => { const url = artifactUrl(run.id, artifact.relativePath); return <figure key={artifact.id}><button onClick={() => setZoom(url)}><img src={url} alt={artifact.label} /><span><ZoomIn />放大</span></button><figcaption><strong>{artifact.label}</strong><small>{artifact.viewport} · {artifact.testCaseId}</small><a href={url} download><Download /></a></figcaption></figure>; })}</div><div className="evidence-logs"><h3><FileWarning />当前测试浏览器日志</h3>{evidence.logs.length ? evidence.logs.map((log, logIndex) => <div key={`${log.message}-${logIndex}`} className={`log-${log.type}`}><code>{log.type}</code><p>{log.message}<small>{log.viewport}{typeof log.stepIndex === "number" ? ` · 步骤 ${log.stepIndex + 1}` : ""}</small></p></div>) : <p className="muted">当前需求未捕获测试日志</p>}<h3><Network />当前测试网络失败</h3>{evidence.requestFailures.length ? evidence.requestFailures.map((failure) => <div key={`${failure.url}-${failure.timestamp}`}><code>{failure.method}</code><p>{failure.url}<small>{failure.reason}</small></p></div>) : <p className="muted">当前需求未捕获网络请求失败</p>}</div></article>;
  };
  const globalView = (projectId: ProjectId, index: number) => { const project = result.projectResults[index]; if (!project) return null; const evidence = globalEvidenceForProject(project); return <article className="evidence-project global-evidence" key={projectId}><header><span className="project-letter">{projectId === "project-a" ? "A" : "B"}</span><div><small>GLOBAL / BASE</small><h2>{run.projects[index]?.name ?? projectId}</h2></div></header><div className="evidence-images">{evidence.artifacts.filter((item) => item.type === "screenshot").map((artifact) => { const url = artifactUrl(run.id, artifact.relativePath); return <figure key={artifact.id}><button onClick={() => setZoom(url)}><img src={url} alt={artifact.label} /><span><ZoomIn />放大</span></button><figcaption><strong>{artifact.label}</strong><small>{artifact.viewport} · BASE</small><a href={url} download><Download /></a></figcaption></figure>; })}</div><div className="evidence-logs"><h3><FileWarning />首页与无法归属的日志</h3>{evidence.logs.length ? evidence.logs.map((log, logIndex) => <div key={`${log.message}-${logIndex}`}><code>{log.type}</code><p>{log.message}</p></div>) : <p className="muted">无全局浏览器错误</p>}<h3><Network />无法归属的网络失败</h3>{evidence.requestFailures.length ? evidence.requestFailures.map((failure) => <div key={`${failure.url}-${failure.timestamp}`}><code>{failure.method}</code><p>{failure.url}<small>{failure.reason}</small></p></div>) : <p className="muted">无全局网络失败</p>}</div></article>; };
  return <motion.div className="page evidence-page" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
    <PageHeader eyebrow="TRACEABLE QUALITY EVIDENCE" title="需求追踪与证据" description="未测试不等于失败；没有可执行证据不能判定需求已经实现。" actions={<Link className="button ghost" to={`/runs/${id}/results`}><GitCompareArrows />返回对比</Link>} />
    {error && <ErrorNotice message={error} />}
    <div className="evidence-layout"><aside className="matrix-nav panel"><div className="matrix-filter"><Filter /><select value={filter} onChange={(event) => setFilter(event.target.value as RequirementStatus | "all")}><option value="all">全部状态</option><option value="passed">通过</option><option value="partial">部分通过</option><option value="failed">失败</option><option value="untested">未测试</option></select></div>{filtered.map((entry) => <button className={entry.requirement.id === selected?.requirement.id ? "active" : ""} key={entry.requirement.id} onClick={() => setSelectedId(entry.requirement.id)}><span>{entry.requirement.id}</span><strong>{entry.requirement.title}</strong><div><StatusBadge status={entry.projectA.status} /><StatusBadge status={entry.projectB.status} /></div></button>)}</aside><section className="evidence-detail">{selected ? <><div className="requirement-head panel"><div><span className="eyebrow">{selected.requirement.id} · {selected.requirement.priority}</span><h2>{selected.requirement.title}</h2><p>{selected.requirement.description ?? "没有补充描述"}</p></div><div><small>关联测试</small><strong>{selected.testCaseIds.length}</strong></div></div><div className="expected-panel panel"><span className="eyebrow">TEST CONTRACT</span>{tests.map((testCase) => <div key={testCase.id}><strong>{testCase.id} · {testCase.name}</strong><p>{testCase.steps.map((step) => step.action).join(" → ")} · {(testCase.viewports ?? ["desktop"]).join(" / ")}</p></div>)}</div><div className="evidence-compare">{projectView("project-a", 0)}{projectView("project-b", 1)}</div><div className="global-evidence-heading"><span className="eyebrow">GLOBAL EVIDENCE</span><h2>全局与 BASE 证据</h2><p>这里仅显示首页、启动阶段和无法归属具体测试的证据，不重复计入需求。</p></div><div className="evidence-compare">{globalView("project-a", 0)}{globalView("project-b", 1)}</div></> : <EmptyState title="没有匹配需求" body="调整左侧状态筛选器。" />}</section></div>
    {zoom && <button className="image-lightbox" onClick={() => setZoom(null)} aria-label="关闭图片预览"><img src={zoom} alt="放大的测试截图" /><span>点击任意位置关闭</span></button>}
  </motion.div>;
}
