import { useEffect, useState } from "react";
import { AlertTriangle, Check, Clipboard, Download, ExternalLink, FileJson, FileText, GitCompareArrows, ShieldCheck, ShieldX } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import { finalizeEvaluation, type BenchmarkRun, type ProjectId, type ScoreBreakdown, type ScoreDimension } from "@agentbench/shared";
import { api, messageOf } from "../services/api";
import { ErrorNotice, PageHeader, ScoreBar, StatusBadge } from "../components/Ui";

const dimensions: Array<[keyof ScoreBreakdown, ScoreDimension, string]> = [["effectiveRequirementScore", "requirement", "有效需求得分"], ["criticalInteractions", "criticalInteractions", "关键交互"], ["stability", "stability", "运行稳定性"], ["performance", "performance", "性能表现"], ["responsive", "responsive", "响应式适配"], ["accessibility", "accessibility", "无障碍质量"], ["baseQuality", "baseQuality", "基础质量"]];
const confidenceLabel = { high: "高", medium: "中", low: "低" } as const;
const releaseLabel = { ready: "可以发布", conditional: "有条件发布", blocked: "阻断", "not-comparable": "不可比较" } as const;

export function ResultPage() {
  const { id = "" } = useParams();
  const [run, setRun] = useState<BenchmarkRun | null>(null);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const [explanation, setExplanation] = useState<{ projectId: ProjectId; dimension: ScoreDimension; label: string } | null>(null);
  useEffect(() => { api.getRun(id).then(setRun).catch((value) => setError(messageOf(value))); }, [id]);
  const result = run?.results;
  if (!result || !run) return <div className="page"><PageHeader eyebrow="COMPARISON RESULT" title="项目对比结果" />{error ? <ErrorNotice message={error} /> : <div className="loading-line">正在读取评分与证据…</div>}</div>;
  const evaluation = result.evaluation ?? finalizeEvaluation({ projectResults: result.projectResults, scores: result.scores, requirementMatrix: result.requirementMatrix, requirements: run.requirements, testCases: run.testCases, projectNames: { "project-a": run.projects[0].name, "project-b": run.projects[1].name } });
  const recommendedId = evaluation.recommendedDevelopmentBase;
  const copyPrompt = async () => { await navigator.clipboard.writeText(evaluation.nextIterationPrompt); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  const scoreLabel = (value: number | null) => value === null ? "不可评分" : value.toFixed(1);
  const scoreBar = (projectId: ProjectId, score: ScoreBreakdown, key: keyof ScoreBreakdown, dimension: ScoreDimension, label: string) => <button className="score-explain-trigger" type="button" key={key} onClick={() => setExplanation({ projectId, dimension, label })}><ScoreBar label={label} value={Number(score[key])} {...(key === "performance" && score.performanceEstimated ? { detail: "Lighthouse 未执行 · 固定规则估算且限制上限" } : {})} /><span>查看计算依据</span></button>;
  return <motion.div className="page" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}>
    <PageHeader eyebrow="COMPARISON RESULT" title={run.name} description={`生成于 ${new Date(result.generatedAt).toLocaleString("zh-CN")}`} actions={<Link className="button ghost" to={`/runs/${id}/evidence`}><ExternalLink />查看证据中心</Link>} />
    {error && <ErrorNotice message={error} />}
    <section className={`recommendation-card ${evaluation.comparable ? `release-${evaluation.releaseJudgement}` : "not-comparable"}`}><div><span className="eyebrow">{evaluation.releaseJudgement === "blocked" ? "RELEASE BLOCKED" : evaluation.comparable ? "DEVELOPMENT BASE" : "NOT COMPARABLE"}</span><h2>{!evaluation.comparable ? "当前评测不可比较" : evaluation.releaseJudgement === "blocked" ? `当前版本存在发布阻断；建议继续基于 ${evaluation.recommendedProjectName} 修复` : `建议继续基于 ${evaluation.recommendedProjectName} 开发`}</h2><ul>{evaluation.recommendationReasons.map((reason) => <li key={reason}>{evaluation.comparable ? <Check /> : <AlertTriangle />}{reason}</li>)}</ul>{evaluation.releaseRecommendedProject && <p className="release-ready-note">达到发布条件：{run.projects[evaluation.releaseRecommendedProject === "project-a" ? 0 : 1].name}</p>}</div><div className="recommend-score"><small>DECISION SCORE</small><strong>{evaluation.comparable && recommendedId ? scoreLabel(evaluation.decisionScore) : "—"}</strong><span>{evaluation.comparable && recommendedId ? "/ 100" : "不可比较"}</span></div></section>
    <section className="assessment-grid"><article className="panel assessment-card"><ShieldCheck /><div><small>强证据覆盖率</small><strong>{evaluation.strongEvidenceCoverage.toFixed(1)}%</strong><p>执行 {evaluation.executionCoverage.toFixed(1)}% · 断言 {evaluation.assertionCoverage.toFixed(1)}%</p></div></article><article className={`panel assessment-card confidence-${evaluation.confidence}`}><ShieldCheck /><div><small>评测置信度</small><strong>{confidenceLabel[evaluation.confidence]}</strong><p>{evaluation.confidenceReasons.join("；")}</p></div></article><article className={`panel assessment-card release-${evaluation.releaseJudgement}`}><ShieldCheck /><div><small>发布判断</small><strong>{releaseLabel[evaluation.releaseJudgement]}</strong><p>{evaluation.releaseReasons.join("；")}</p></div></article></section>
    <section className="comparison-score-grid">{(["project-a", "project-b"] as ProjectId[]).map((projectId, index) => { const score = result.scores[projectId]; const projectResult = result.projectResults[index]; return <article className={`panel score-card ${evaluation.comparable && projectId === recommendedId ? "winner" : ""}`} key={projectId}><header><div><span className="project-letter">{projectId === "project-a" ? "A" : "B"}</span><div><small>{run.projects[index]?.sourceAgent ?? "AGENT"}</small><h2>{run.projects[index]?.name}</h2></div></div><div className="big-score"><strong>{scoreLabel(score.total)}</strong><span>{score.total === null ? "STARTUP FAILED" : "PTS"}</span></div></header><div className="score-bars">{score.total === null ? <div className="unscored-notice"><AlertTriangle />项目启动失败，不生成看似正常的综合质量分。</div> : dimensions.map(([key, dimension, label]) => scoreBar(projectId, score, key, dimension, label))}{score.unexecutedChecks.length > 0 && <div className="unexecuted-notice"><strong>未执行：</strong>{score.unexecutedChecks.join("、")}；对应分项已降分并降低置信度。</div>}{score.capReasons.length > 0 && <div className="score-cap-notice"><strong>分数上限：</strong>{score.capReasons.join("；")}</div>}</div><div className="score-stats"><div><small>验证通过率</small><strong>{score.verifiedPassRate.toFixed(1)}%</strong></div><div><small>需求覆盖率</small><strong>{score.requirementCoverage.toFixed(1)}%</strong></div><div><small>有效需求分</small><strong>{score.effectiveRequirementScore.toFixed(1)}</strong></div><div><small>强证据覆盖</small><strong>{score.strongEvidenceCoverage.toFixed(1)}%</strong></div><div><small>关键测试</small><strong>{score.criticalInteractions.toFixed(1)}%</strong></div><div><small>控制台错误</small><strong>{projectResult?.browserLogs.filter((item) => item.type === "error" || item.type === "pageerror").length ?? 0}</strong></div></div></article>; })}</section>
    <section className="panel compact-matrix"><div className="panel-heading"><div><span className="eyebrow">TRACEABILITY SNAPSHOT</span><h2>需求完成与验证覆盖</h2></div><Link to={`/runs/${id}/evidence`}>进入完整矩阵 <ExternalLink /></Link></div><table><thead><tr><th>需求</th><th>测试</th><th>{run.projects[0].name}</th><th>{run.projects[1].name}</th></tr></thead><tbody>{result.requirementMatrix.map((entry) => <tr key={entry.requirement.id}><td><strong>{entry.requirement.id}</strong>{entry.requirement.title}<small>{entry.requirement.priority}</small></td><td>{entry.testCaseIds.join(", ") || "无测试"}</td><td><StatusBadge status={entry.projectA.status} /></td><td><StatusBadge status={entry.projectB.status} /></td></tr>)}</tbody></table></section>
    <section className="decision-grid"><article className="panel blocker-panel"><div className="panel-heading"><div><span className="eyebrow">RELEASE BLOCKERS</span><h2>分级阻断问题</h2></div><ShieldX /></div>{(["project-a", "project-b"] as ProjectId[]).map((projectId, index) => { const items = evaluation.blockers.filter((item) => item.projectId === projectId); return <div className="blocker-group" key={projectId}><h3>{run.projects[index]?.name}</h3>{items.length ? <ol>{items.map((item) => <li key={item.id} className={`blocker-${item.severity}`}><strong>{item.severity.toUpperCase()}</strong> · {item.source} · {item.message}</li>)}</ol> : <p className="clean-result"><Check />未发现规则定义的阻断问题</p>}</div>; })}</article><article className="panel prompt-panel"><div className="panel-heading"><div><span className="eyebrow">NEXT ITERATION</span><h2>下一轮修改任务</h2></div><button onClick={() => void copyPrompt()}>{copied ? <Check /> : <Clipboard />}{copied ? "已复制" : "复制"}</button></div><pre>{evaluation.nextIterationPrompt}</pre></article></section>
    <section className="export-bar"><div><Download /><span><strong>导出独立报告</strong><small>默认隐藏绝对路径；HTML 内嵌截图，可离线打开</small></span></div><div><a className="button ghost" href={`/api/runs/${id}/export/html`}><GitCompareArrows />HTML</a><a className="button ghost" href={`/api/runs/${id}/export/markdown`}><FileText />Markdown</a><a className="button ghost" href={`/api/runs/${id}/export/json`}><FileJson />JSON</a></div></section>
    {explanation && <div className="score-drawer-backdrop" onClick={() => setExplanation(null)}><aside className="score-drawer" onClick={(event) => event.stopPropagation()}><button className="drawer-close" onClick={() => setExplanation(null)}>关闭</button><span className="eyebrow">SCORE EXPLANATION</span><h2>{run.projects[explanation.projectId === "project-a" ? 0 : 1].name} · {explanation.label}</h2>{(() => { const detail = result.scores[explanation.projectId].explanations[explanation.dimension]; return detail ? <><dl><div><dt>基础值</dt><dd>{detail.baseValue ?? "—"}</dd></div><div><dt>最终值</dt><dd>{detail.finalValue ?? "—"}</dd></div></dl><h3>扣分项</h3><ul>{detail.deductions.length ? detail.deductions.map((item) => <li key={item.label}>{item.label}<strong>{item.value.toFixed(1)}</strong></li>) : <li>无</li>}</ul><h3>加分项</h3><ul>{detail.bonuses.length ? detail.bonuses.map((item) => <li key={item.label}>{item.label}<strong>+{item.value.toFixed(1)}</strong></li>) : <li>无</li>}</ul><h3>分数上限</h3><ul>{detail.caps.length ? detail.caps.map((item) => <li key={item.label}>{item.label}<strong>{item.limit}</strong></li>) : <li>无</li>}</ul></> : <p>该维度暂无解释数据。</p>; })()}</aside></div>}
  </motion.div>;
}
